### ISSUE TITLE
Faraday upgrade

### ISSUE THREAD

**Issue by joergd** [ruby-amqp/rabbitmq_http_api_client#46] opened 2020-07-08 05:16 UTC
This is still requiring quite an old version of Faraday, which is forcing me to use older versions of other gems in my project.

**Comment by michaelklishin** [comment] 2020-07-08 09:19
Duplicate of https://github.com/ruby-amqp/rabbitmq_http_api_client/pull/45.

This is open source software, consider submitting a PR next time instead of asking others to make a reasonably straightforward change.

**Closed by michaelklishin** 2020-07-08 09:19 UTC

**Comment by michaelklishin** [comment] 2020-07-08 09:41
`1.14.0` is [up on RubyGems](https://rubygems.org/gems/rabbitmq_http_api_client/versions/1.14.0).

**Comment by joergd** [comment] 2020-07-08 12:44
Thank you - much appreciated. And yes you're right - it was a bit lazy of me.
